name: Update gist with Date

on:
  schedule:
    - cron: "0 0 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: kf-liu/date-box@master
        env:
          TYPE: DAY
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: c25b431e339519979478d0e9610e8b89
          RECORDS: "2024-10-22 _ 정보처리자격증 취득 | 0 * 28 12 * _ 최종 프로젝트 발표
